Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
staring_points = jnp.array([
    [-15.0, 0.0],
    [-14.0, 6.0], [-14.0, -6.0],
    [-11.0, 4.0], [-11.0, -4.0],
    [-10.0, 7.0], [-10.0, -7.0], [-10.0, 0.0], [-10.0, 5.0], [-10.0, -5.0],
    [-6.0, 8.0], [-6.0, -8.0], [-6.0, 5.0], [-6.0, -5.0], [-6.0, 0.0],
    [-8.0, 2.0], [-8.0, -2.0],
    [-5.0, 0.0],
    [-4.0, 0.0],
    [-2.0, 0.0],
    [0.0, 2.0], [0.0, 3.0], [0.0, 0.5], [0.0, 8.0], [0.0, -8.0],
    [2.0, 6.0], [2.0, -6.0],
    [5.0, 0.0],
    [6.0, 0.0],
    [7.0, 6.0], [7.0, -6.0],
    [8.0, 0.0],
    [10.0, 2.0], [10.0, -2.0],
    [11.0, 6.0], [11.0, -6.0],
    [14.0, 2.0], [14.0, -2.0]
])

paths = []
values = []
stopping_conditions = []

for start in staring_points:
    p, v, s = zero_contour_finder(
        v_and_g_inv_mag,
        start,
        delta=0.01,
        max_iter=20,
        tol=1e-14
    )
    paths.append(p)
    values.append(v)
    stopping_conditions.append(s)

# unique stopping conditions
print(Counter([tuple(s.tolist()) for s in stopping_conditions]))

# maximum deviation from zero along any contour
jnp.array([jnp.abs(v).max() for v in values]).max()

------------------

----- stderr -----
No zero contour found after 5*max_newton (25) iterations
------------------

[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[13][39m[32m, line 39[39m
[32m     36[39m     stopping_conditions.append(s)
[32m     38[39m [38;5;66;03m# unique stopping conditions[39;00m
[32m---> [39m[32m39[39m [38;5;28mprint[39m(Counter([43m[[49m[38;5;28;43mtuple[39;49m[43m([49m[43ms[49m[43m.[49m[43mtolist[49m[43m([49m[43m)[49m[43m)[49m[43m [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43ms[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[43mstopping_conditions[49m[43m][49m))
[32m     41[39m [38;5;66;03m# maximum deviation from zero along any contour[39;00m
[32m     42[39m jnp.array([jnp.abs(v).max() [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m values]).max()

[36mCell[39m[36m [39m[32mIn[13][39m[32m, line 39[39m, in [36m<listcomp>[39m[34m(.0)[39m
[32m     36[39m     stopping_conditions.append(s)
[32m     38[39m [38;5;66;03m# unique stopping conditions[39;00m
[32m---> [39m[32m39[39m [38;5;28mprint[39m(Counter([[38;5;28mtuple[39m([43ms[49m[43m.[49m[43mtolist[49m()) [38;5;28;01mfor[39;00m s [38;5;129;01min[39;00m stopping_conditions]))
[32m     41[39m [38;5;66;03m# maximum deviation from zero along any contour[39;00m
[32m     42[39m jnp.array([jnp.abs(v).max() [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m values]).max()

[31mAttributeError[39m: 'NoneType' object has no attribute 'tolist'

